### ISSUE TITLE
COT-02 : Inaccurate Quorum and Voting Ratio Calculations

### ISSUE THREAD

**Issue by kerber0x** [White-Whale-Defi-Platform/contracts#166]

**Comment by CyberHoward** [comment]
We need to be able to set the staked amount before the end of the poll to prevent the following attack:
Buy lots of tokens right before the end of the poll
Stake them
Don’t vote
Poll won’t reach quorum so you prevented the vote from passing
Sell tokens again

The scenario mentioned in the report, specifically:
“Timestamp 2: the total balance becomes 400 and there are no new stakers.”
Is incorrect if the “total balance” is understood as the staked amount used when calculating the quorum. The total balance can not be changed after being set at some time before the end of the poll. This setting is done automatically at L515 when voting or can be triggered manually by snapshot_poll at L720.
